<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ToolsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tools')->insert([
            [
                'name' => 'React',
                'category' => json_encode(['Web Development']),
                'language' => 'JavaScript/TypeScript',
                'description' => 'A JavaScript library for building user interfaces.',
                'documentation_url' => 'https://reactjs.org/docs/getting-started.html',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Vue.js',
                'category' => json_encode(['Web Development']),
                'language' => 'JavaScript/TypeScript',
                'description' => 'A progressive framework for building user interfaces.',
                'documentation_url' => 'https://vuejs.org/v2/guide/',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],

            [
                'name' => 'Eva Design System',
                'category' => json_encode(['color palette']),
                'language' => 'N/A',
                'documentation_url' => 'https://colors.eva.design/',
                'description' => 'A design system that provides a consistent interface for applications.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Feather Icons',
                'category' => json_encode(['icons']),
                'language' => 'N/A',
                'documentation_url' => 'https://feathericons.com/',
                'description' => 'A collection of beautiful open-source icons.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Boxicons',
                'category' => json_encode(['icons']),
                'language' => 'N/A',
                'documentation_url' => 'https://boxicons.com/',
                'description' => 'A free collection of carefully crafted icons.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Polaris Icons',
                'category' => json_encode(['icons', 'components', 'layouts']),
                'language' => 'N/A',
                'documentation_url' => 'https://polaris.shopify.com/icons',
                'description' => 'A set of icons designed for Shopify applications.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Pigment',
                'category' => json_encode(['color palette']),
                'language' => 'N/A',
                'documentation_url' => 'https://pigment.shapefactory.co/',
                'description' => 'A tool for generating color palettes.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'LOL Colors',
                'category' => json_encode(['color palette']),
                'language' => 'N/A',
                'documentation_url' => 'https://www.webdesignrankings.com/resources/lolcolors/',
                'description' => 'A resource for color palettes inspired by the game League of Legends.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Daisy UI',
                'category' => json_encode(['component', 'tailwind']),
                'language' => 'N/A',
                'documentation_url' => 'https://daisyui.com/docs/install/',
                'description' => 'A component library built on Tailwind CSS.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'React Icons',
                'category' => json_encode(['icons', 'reactjs', 'nextjs']),
                'language' => 'N/A',
                'documentation_url' => 'https://react-icons.github.io/react-icons/',
                'description' => 'A library for including popular icons in React applications.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Color Safe',
                'category' => json_encode(['color palette', 'accessibility']),
                'language' => 'N/A',
                'documentation_url' => 'http://colorsafe.co/',
                'description' => 'A tool for creating color palettes that meet accessibility standards.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Who Can Use',
                'category' => json_encode(['color palette', 'accessibility']),
                'language' => 'N/A',
                'documentation_url' => 'https://www.whocanuse.com/',
                'description' => 'A tool that helps users check color contrast ratios.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'A11y Project',
                'category' => json_encode(['accessibility']),
                'language' => 'N/A',
                'documentation_url' => 'https://www.a11yproject.com/',
                'description' => 'A community-driven effort to improve web accessibility.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Accessible Brand Colors',
                'category' => json_encode(['accessibility']),
                'language' => 'N/A',
                'documentation_url' => 'https://abc.useallfive.com/',
                'description' => 'A resource for accessible color choices for branding.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Contrast Grid',
                'category' => json_encode(['accessibility']),
                'language' => 'N/A',
                'documentation_url' => 'https://contrast-grid.eightshapes.com/?version=1.1.0&background-colors=&foreground-colors=%23FFFFFF%2C%20White%0D%0A%23F2F2F2%0D%0A%23DDDDDD%0D%0A%23CCCCCC%0D%0A%23888888%0D%0A%23404040%2C%20Charcoal%0D%0A%23000000%2C%20Black%0D%0A%232F78C5%2C%20Effective%20on%20Extremes%0D%0A%230F60B6%2C%20Effective%20on%20Lights%0D%0A%23398EEA%2C%20Ineffective%0D%0A&es-color-form__tile-size=compact&es-color-form__show-contrast=aaa&es-color-form__show-contrast=aa&es-color-form__show-contrast=aa18&es-color-form__show-contrast=dnp',
                'description' => 'A tool for checking color contrast between elements.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Figma',
                'category' => json_encode(['design tools']),
                'language' => 'N/A',
                'documentation_url' => 'https://www.figma.com/',
                'description' => 'A web-based UI design tool for collaborative design.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Sketch',
                'category' => json_encode(['design tools']),
                'language' => 'N/A',
                'documentation_url' => 'https://www.sketch.com/',
                'description' => 'A vector graphics editor for macOS for designing interfaces.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Bootstrap',
                'category' => json_encode(['CSS Framework']),
                'language' => 'HTML, CSS, JavaScript',
                'documentation_url' => 'https://getbootstrap.com/',
                'description' => 'A popular HTML, CSS, and JS framework for developing responsive, mobile-first projects on the web.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Vue.js',
                'category' => json_encode(['JavaScript Framework']),
                'language' => 'JavaScript',
                'documentation_url' => 'https://vuejs.org/',
                'description' => 'A progressive framework for building user interfaces.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Tailwind CSS',
                'category' => json_encode(['CSS Framework']),
                'language' => 'CSS',
                'documentation_url' => 'https://tailwindcss.com/',
                'description' => 'A utility-first CSS framework for creating custom designs without having to leave your HTML.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Django',
                'category' => json_encode(['Web Framework']),
                'language' => 'Python',
                'documentation_url' => 'https://www.djangoproject.com/',
                'description' => 'A high-level Python web framework that encourages rapid development and clean, pragmatic design.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Flask',
                'category' => json_encode(['Web Framework']),
                'language' => 'Python',
                'documentation_url' => 'https://flask.palletsprojects.com/',
                'description' => 'A lightweight WSGI web application framework in Python.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Angular',
                'category' => json_encode(['JavaScript Framework']),
                'language' => 'TypeScript',
                'documentation_url' => 'https://angular.io/',
                'description' => 'A platform for building mobile and desktop web applications.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Laravel',
                'category' => json_encode(['PHP Framework']),
                'language' => 'PHP',
                'documentation_url' => 'https://laravel.com/',
                'description' => 'A web application framework with expressive, elegant syntax.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Express.js',
                'category' => json_encode(['Web Framework']),
                'language' => 'JavaScript',
                'documentation_url' => 'https://expressjs.com/',
                'description' => 'A minimal and flexible Node.js web application framework that provides a robust set of features.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Ruby on Rails',
                'category' => json_encode(['Web Framework']),
                'language' => 'Ruby',
                'documentation_url' => 'https://rubyonrails.org/',
                'description' => 'A web-application framework that includes everything needed to create database-backed web applications.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Spring Boot',
                'category' => json_encode(['Java Framework']),
                'language' => 'Java',
                'documentation_url' => 'https://spring.io/projects/spring-boot',
                'description' => 'A framework that simplifies the setup of new Spring applications.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Gatsby',
                'category' => json_encode(['Static Site Generator']),
                'language' => 'JavaScript',
                'documentation_url' => 'https://www.gatsbyjs.com/',
                'description' => 'A free and open-source framework based on React that helps developers build fast websites.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Next.js',
                'category' => json_encode(['React Framework']),
                'language' => 'JavaScript',
                'documentation_url' => 'https://nextjs.org/',
                'description' => 'A React framework that enables server-side rendering and generating static websites.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Sass',
                'category' => json_encode(['CSS Preprocessor']),
                'language' => 'CSS',
                'documentation_url' => 'https://sass-lang.com/',
                'description' => 'A preprocessor scripting language that is interpreted or compiled into CSS.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Redux',
                'category' => json_encode(['State Management']),
                'language' => 'JavaScript',
                'documentation_url' => 'https://redux.js.org/',
                'description' => 'A predictable state container for JavaScript apps.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Webpack',
                'category' => json_encode(['Module Bundler']),
                'language' => 'JavaScript',
                'documentation_url' => 'https://webpack.js.org/',
                'description' => 'A static module bundler for modern JavaScript applications.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'PostCSS',
                'category' => json_encode(['CSS Tool']),
                'language' => 'CSS',
                'documentation_url' => 'https://postcss.org/',
                'description' => 'A tool for transforming CSS with JavaScript plugins.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Cypress',
                'category' => json_encode(['Testing Framework']),
                'language' => 'JavaScript',
                'documentation_url' => 'https://www.cypress.io/',
                'description' => 'A next generation front end testing tool built for the modern web.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Jest',
                'category' => json_encode(['Testing Framework']),
                'language' => 'JavaScript',
                'documentation_url' => 'https://jestjs.io/',
                'description' => 'A delightful JavaScript testing framework with a focus on simplicity.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
            [
                'name' => 'Figma',
                'category' => json_encode(['Design Tool']),
                'language' => 'N/A',
                'documentation_url' => 'https://www.figma.com/',
                'description' => 'A collaborative interface design tool.',
                'created_at' => now(),
                'updated_at' => now(),
                'image' => 'default.jpg',
            ],
        ]);
    }
}
